---
apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  type: NodePort
  ports:
  - name: test1
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: test1

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: test1
 labels:
   app: test1
spec:
 replicas: 1
 selector:
   matchLabels:
     app: test1
 template:
   metadata:
     labels:
       app: test1
   spec:
     imagePullSecrets:
      - name: regcred
     containers:
     - name: test1
       image: okiprasetia/test:latest
       imagePullPolicy: Always
       port:
         - ContainerPort: 80
           protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test1
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: test1
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
